### PR TITLE
Make sure that generated query config is valid

### LINKED ISSUE #403: Running custom journals does not work with Akka.Persistence.Query
**Version Information**
Version of Akka.NET? latest
Which Akka.NET Modules? Akka.Persistence.Sql

**Describe the bug**

When using the following configuration:

```csharp
  builder.WithSqlPersistence(
            autoInitialize: true,
            connectionString: connectionStringForJournalAndSnapshots,
            isDefaultPlugin: false,
            providerName: ProviderName.PostgreSQL,
            pluginIdentifier: OwnershipReadJournal.TYPE_NAME,
            journalBuilder: journalBuilder =>
            {
                journalBuilder.AddWriteEventAdapter<OwnershipDomainTagger>("ownership-domain-tagger",
                    new[] { typeof(IOwnershipDomain) });
            });
```

The HOCON ends up looking like this, which is slightly wrong / weird

```hocon
    persistence : {
      query : {
        journal : {
          ownership : {
            class : "Akka.Persistence.Sql.Query.SqlReadJournalProvider, Akka.Persistence.Sql"
            write-plugin : 
            max-buffer-size : 500
            refresh-interval : 1s
            connection-string : 
            tag-read-mode : TagTable
            journal-sequence-retrieval : {
              batch-size : 10000
              max-tries : 10
              query-delay : 1s
              max-backoff-query-delay : 60s
              ask-timeout : 1s
            }
            provider-name : 
            table-mapping : default
            buffer-size : 5000
            batch-size : 100
            replay-batch-size : 1000
            parallelism : 3
            max-row-by-row-size : 100
            use-clone-connection : true
            tag-separator : ;
            read-isolation-level : unspecified
            dao : "Akka.Persistence.Sql.Journal.Dao.ByteArrayJournalDao, Akka.Persistence.Sql"
            default : {
              schema-name : 
              journal : {
                use-writer-uuid-column : true
                table-name : journal
                columns : {
                  ordering : ordering
                  deleted : deleted
                  persistence-id : persistence_id
                  sequence-number : sequence_number
                  created : created
                  tags : tags
                  message : message
                  identifier : identifier
                  manifest : manifest
                  writer-uuid : writer_uuid
                }
              }
              metadata : {
                table-name : journal_metadata
                columns : {
                  persistence-id : persistence_id
                  sequence-number : sequence_number
                }
              }
              tag : {
                table-name : tags
                columns : {
                  ordering-id : ordering_id
                  tag-value : tag
                  persistence-id : persistence_id
                  sequence-nr : sequence_nr
                }
              }
            }
            sql-server : {
              schema-name : dbo
              journal : {
                use-writer-uuid-column : false
                table-name : EventJournal
                columns : {
                  ordering : Ordering
                  deleted : IsDeleted
                  persistence-id : PersistenceId
                  sequence-number : SequenceNr
                  created : Timestamp
                  tags : Tags
                  message : Payload
                  identifier : SerializerId
                  manifest : Manifest
                }
              }
              metadata : {
                table-name : Metadata
                columns : {
                  persistence-id : PersistenceId
                  sequence-number : SequenceNr
                }
              }
            }
            sqlite : {
              schema-name : 
              journal : {
                use-writer-uuid-column : false
                table-name : event_journal
                columns : {
                  ordering : ordering
                  deleted : is_deleted
                  persistence-id : persistence_id
                  sequence-number : sequence_nr
                  created : timestamp
                  tags : tags
                  message : payload
                  identifier : serializer_id
                  manifest : manifest
                }
              }
              metadata : {
                table-name : journal_metadata
                columns : {
                  persistence-id : persistence_id
                  sequence-number : sequence_nr
                }
              }
            }
            postgresql : {
              schema-name : public
              journal : {
                use-writer-uuid-column : false
                table-name : event_journal
                columns : {
                  ordering : ordering
                  deleted : is_deleted
                  persistence-id : persistence_id
                  sequence-number : sequence_nr
                  created : created_at
                  tags : tags
                  message : payload
                  identifier : serializer_id
                  manifest : manifest
                }
              }
              metadata : {
                table-name : metadata
                columns : {
                  persistence-id : persistence_id
                  sequence-number : sequence_nr
                }
              }
            }
            mysql : {
              schema-name : 
              journal : {
                use-writer-uuid-column : false
                table-name : event_journal
                columns : {
                  ordering : ordering
                  deleted : is_deleted
                  persistence-id : persistence_id
                  sequence-number : sequence_nr
                  created : created_at
                  tags : tags
                  message : payload
                  identifier : serializer_id
                  manifest : manifest
                }
              }
              metadata : {
                table-name : metadata
                columns : {
                  persistence-id : persistence_id
                  sequence-number : sequence_nr
                }
              }
            }
          }
        }
      }
      snapshot-store : {
        ownership : {
          class : "Akka.Persistence.Sql.Snapshot.SqlSnapshotStore, Akka.Persistence.Sql"
          plugin-dispatcher : akka.persistence.dispatchers.default-plugin-dispatcher
          connection-string : "Host=localhost;Database=phoenix-persistence-ownership-development;Username=postgres;Password=postgres;Port=5432;Maximum Pool Size=100;Pooling=True"
          provider-name : PostgreSQL
          use-clone-connection : true
          table-mapping : default
          serializer : 
          dao : "Akka.Persistence.Sql.Snapshot.ByteArraySnapshotDao, Akka.Persistence.Sql"
          auto-initialize : on
          warn-on-auto-init-fail : true
          read-isolation-level : unspecified
          write-isolation-level : unspecified
          default : {
            schema-name : 
            snapshot : {
              table-name : snapshot
              columns : {
                persistence-id : persistence_id
                sequence-number : sequence_number
                created : created
                snapshot : snapshot
                manifest : manifest
                serializerId : serializer_id
              }
            }
          }
          sql-server : {
            schema-name : dbo
            snapshot : {
              table-name : SnapshotStore
              columns : {
                persistence-id : PersistenceId
                sequence-number : SequenceNr
                created : Timestamp
                snapshot : Snapshot
                manifest : Manifest
                serializerId : SerializerId
              }
            }
          }
          sqlite : {
            schema-name : 
            snapshot : {
              table-name : snapshot
              columns : {
                persistence-id : persistence_id
                sequence-number : sequence_nr
                snapshot : payload
                manifest : manifest
                created : created_at
                serializerId : serializer_id
              }
            }
          }
          postgresql : {
            schema-name : public
            snapshot : {
              table-name : snapshot_store
              columns : {
                persistence-id : persistence_id
                sequence-number : sequence_nr
                snapshot : payload
                manifest : manifest
                created : created_at
                serializerId : serializer_id
              }
            }
          }
          mysql : {
            schema-name : 
            snapshot : {
              table-name : snapshot_store
              columns : {
                persistence-id : persistence_id
                sequence-number : sequence_nr
                snapshot : snapshot
                manifest : manifest
                created : created_at
                serializerId : serializer_id
              }
            }
          }
        }
      }
      journal : {
        ownership : {
          class : "Akka.Persistence.Sql.Journal.SqlWriteJournal, Akka.Persistence.Sql"
          plugin-dispatcher : akka.persistence.dispatchers.default-plugin-dispatcher
          connection-string : "Host=localhost;Database=phoenix-persistence-ownership-development;Username=postgres;Password=postgres;Port=5432;Maximum Pool Size=100;Pooling=True"
          provider-name : PostgreSQL
          delete-compatibility-mode : false
          table-mapping : default
          buffer-size : 5000
          batch-size : 100
          db-round-trip-max-batch-size : 1000
          prefer-parameters-on-multirow-insert : false
          replay-batch-size : 1000
          parallelism : 3
          max-row-by-row-size : 100
          use-clone-connection : true
          materializer-dispatcher : akka.actor.default-dispatcher
          tag-write-mode : TagTable
          tag-separator : ;
          auto-initialize : on
          warn-on-auto-init-fail : true
          dao : "Akka.Persistence.Sql.Journal.Dao.ByteArrayJournalDao, Akka.Persistence.Sql"
          serializer : 
          read-isolation-level : unspecified
          write-isolation-level : unspecified
          default : {
            schema-name : 
            journal : {
              use-writer-uuid-column : true
              table-name : journal
              columns : {
                ordering : ordering
                deleted : deleted
                persistence-id : persistence_id
                sequence-number : sequence_number
                created : created
                tags : tags
                message : message
                identifier : identifier
                manifest : manifest
                writer-uuid : writer_uuid
              }
            }
            metadata : {
              table-name : journal_metadata
              columns : {
                persistence-id : persistence_id
                sequence-number : sequence_number
              }
            }
            tag : {
              table-name : tags
              columns : {
                ordering-id : ordering_id
                tag-value : tag
                persistence-id : persistence_id
                sequence-nr : sequence_nr
              }
            }
          }
          sql-server : {
            schema-name : dbo
            journal : {
              use-writer-uuid-column : false
              table-name : EventJournal
              columns : {
                ordering : Ordering
                deleted : IsDeleted
                persistence-id : PersistenceId
                sequence-number : SequenceNr
                created : Timestamp
                tags : Tags
                message : Payload
                identifier : SerializerId
                manifest : Manifest
              }
            }
            metadata : {
              table-name : Metadata
              columns : {
                persistence-id : PersistenceId
                sequence-number : SequenceNr
              }
            }
          }
          sqlserver : {
            schema-name : dbo
            journal : {
              use-writer-uuid-column : false
              table-name : EventJournal
              columns : {
                ordering : Ordering
                deleted : IsDeleted
                persistence-id : PersistenceId
                sequence-number : SequenceNr
                created : Timestamp
                tags : Tags
                message : Payload
                identifier : SerializerId
                manifest : Manifest
              }
            }
            metadata : {
              table-name : Metadata
              columns : {
                persistence-id : PersistenceId
                sequence-number : SequenceNr
              }
            }
          }
          sqlite : {
            schema-name : 
            journal : {
              use-writer-uuid-column : false
              table-name : event_journal
              columns : {
                ordering : ordering
                deleted : is_deleted
                persistence-id : persistence_id
                sequence-number : sequence_nr
                created : timestamp
                tags : tags
                message : payload
                identifier : serializer_id
                manifest : manifest
              }
            }
            metadata : {
              table-name : journal_metadata
              columns : {
                persistence-id : persistence_id
                sequence-number : sequence_nr
              }
            }
          }
          postgresql : {
            schema-name : public
            journal : {
              use-writer-uuid-column : false
              table-name : event_journal
              columns : {
                ordering : ordering
                deleted : is_deleted
                persistence-id : persistence_id
                sequence-number : sequence_nr
                created : created_at
                tags : tags
                message : payload
                identifier : serializer_id
                manifest : manifest
              }
            }
            metadata : {
              table-name : metadata
              columns : {
                persistence-id : persistence_id
                sequence-number : sequence_nr
              }
            }
          }
          mysql : {
            schema-name : 
            journal : {
              use-writer-uuid-column : false
              table-name : event_journal
              columns : {
                ordering : ordering
                deleted : is_deleted
                persistence-id : persistence_id
                sequence-number : sequence_nr
                created : created_at
                tags : tags
                message : payload
                identifier : serializer_id
                manifest : manifest
              }
            }
            metadata : {
              table-name : metadata
              columns : {
                persistence-id : persistence_id
                sequence-number : sequence_nr
              }
            }
          }
          event-adapters : {
            ownership-domain-tagger : "netfile.phoenix.ownership.actors.OwnershipDomainTagger, netfile.phoenix.ownership.actors"
          }
          event-adapter-bindings : {
            "netfile.phoenix.ownership.domain.IOwnershipDomain, netfile.phoenix.ownership.domain" : [ownership-domain-tagger]
          }
        }
      }
    }
```

The suspicious looking part are the Akka.Persistence.Query settings - looks like there is no Provider or connection string.

```
[11:13:40 ERR] An exception occured inside SelectAsync while executing Task. Supervision strategy: Stop
System.AggregateException: One or more errors occurred. (DataProvider '' not found.)
 ---> LinqToDB.LinqToDBException: DataProvider '' not found.
   at LinqToDB.Data.DataConnection.GetDataProviderEx(String providerName, String connectionString)
   at LinqToDB.Data.DataConnection.ConfigurationApplier.Apply(DataConnection dataConnection, ConnectionOptions options)
   at LinqToDB.Data.ConnectionOptions.LinqToDB.Common.IApplicable<LinqToDB.Data.DataConnection>.Apply(DataConnection obj)
   at LinqToDB.DataOptions.Apply(DataConnection dataConnection)
   at LinqToDB.Data.DataConnection..ctor(DataOptions options)
   at Akka.Persistence.Sql.Db.AkkaPersistenceDataConnectionFactory.<>c__DisplayClass4_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Akka.Persistence.Sql.Db.AkkaPersistenceDataConnectionFactory.GetConnection()
   at Akka.Persistence.Sql.Extensions.ConnectionFactoryExtensions.ExecuteWithTransactionAsync[TState,T](AkkaPersistenceDataConnectionFactory factory, TState state, IsolationLevel level, CancellationToken token, Func`4 handler)
   at Akka.Persistence.Sql.Query.Dao.BaseByteReadArrayJournalDao.<>c.<<JournalSequence>b__7_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Akka.Actor.PipeToSupport.PipeTo[T](Task`1 taskToPipe, ICanTell recipient, Boolean useConfigureAwait, IActorRef sender, Func`2 success, Func`2 failure)
```

This happens while attempting to run Akka.Persistence.Query to do projections.

**Expected behavior**

The non-default journal should be able to run queries normally.

```csharp
// uses the same custom persistence id, but fully-qualified "akka.persistence.query.journal.ownershp"
var readJournal = Context.System.ReadJournalFor<SqlReadJournal>(OwnershipReadJournal.Identifier);;
```

**Actual behavior**

Crashes at startup

**Additional context**

Worth noting: this code also crashes when we have a default Akka.Persistence.Sql journal specified in addition to this custom journal. When we make our custom journal the default, everything works.

### PR DESCRIPTION
**Pull request by Arkatufus**
Fixes #403

## Changes

* Fix missing query configuration generation

### CODE REVIEW

**Comment by Arkatufus** [comment]
~~Still need end-to-end test to make sure that queries on custom journal options works properly~~

**Comment by Arkatufus** [comment]
Added end-to-end test, ready for review

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs [hunk 1]
```diff
@@ -0,0 +1,275 @@
...
+        private sealed class MyPersistenceActor : ReceivePersistentActor
+        {
+            private List<int> _values = new();
+            private IActorRef? _sender;
+
+            public MyPersistenceActor(string persistenceId)
+            {
+                PersistenceId = persistenceId;
+                JournalPluginId = "akka.persistence.journal.sql";
+                SnapshotPluginId = "akka.persistence.snapshot-store.sql";
```
Comment (Arkatufus) [inline src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:202]: The first persistence actor uses the default plugin

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs [hunk 2]
```diff
@@ -0,0 +1,275 @@
...
+        private sealed class MyCustomPersistenceActor : ReceivePersistentActor
+        {
+            private List<int> _values = new();
+            private IActorRef? _sender;
+
+            public MyCustomPersistenceActor(string persistenceId)
+            {
+                PersistenceId = persistenceId;
+                JournalPluginId = "akka.persistence.journal.custom";
+                SnapshotPluginId = "akka.persistence.snapshot-store.custom";
```
Comment (Arkatufus) [inline src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:243]: The second persistence actor uses the non-default custom journal and snapshot plugin

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs [hunk 3]
```diff
@@ -0,0 +1,275 @@
...
+
+            // Probe the database directly to make sure that all tables were created properly
+            var tables = await GetTableNamesAsync(_fixture.ConnectionString);
+
+            tables.Should().Contain("journal");
+            tables.Should().Contain("tags");
+            tables.Should().Contain("snapshot");
+            tables.Should().Contain("journal2");
+            tables.Should().Contain("tags2");
+            tables.Should().Contain("snapshot2");
```
Comment (Arkatufus) [inline src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:173]: Testing that all tables were created properly

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs [hunk 4]
```diff
@@ -0,0 +1,275 @@
...
+            probe.ExpectNext<EventEnvelope>(p => p.PersistenceId == PId && p.SequenceNr == 2L && p.Event.Equals(2));
+            await probe.CancelAsync();
+
+            var customReadJournal = Sys.ReadJournalFor<SqlReadJournal>("akka.persistence.query.journal.custom");
+            var customSource = customReadJournal.AllEvents(Offset.NoOffset());
+            var customProbe = customSource.RunWith(this.SinkProbe<EventEnvelope>(), Sys.Materializer());
+            customProbe.Request(2);
+            customProbe.ExpectNext<EventEnvelope>(p => p.PersistenceId == PId && p.SequenceNr == 1L && p.Event.Equals(1));
+            customProbe.ExpectNext<EventEnvelope>(p => p.PersistenceId == PId && p.SequenceNr == 2L && p.Event.Equals(2));
+            await customProbe.CancelAsync();
```
Comment (Arkatufus) [inline src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:163]: Checking that query works with a non-default journal and snapshot

**Review by Arkatufus — COMMENTED** [review]
Self review

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs (hunk 3 above)
Comment (Arkatufus) [reply src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:173]: "journal-metadata" table were not created because we're not using compatibility mode

File: src/Akka.Persistence.Sql.Hosting.Tests/ConfigExtensions.cs
Comment (Aaronontheweb) [inline src/Akka.Persistence.Sql.Hosting.Tests/ConfigExtensions.cs:1]: LGTM

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs [hunk 5]
```diff
@@ -0,0 +1,275 @@
...
+            await _fixture.InitializeAsync();
+        }
+
+        protected override void ConfigureAkka(AkkaConfigurationBuilder builder, IServiceProvider provider)
+        {
+            builder
+                .WithSqlPersistence(
+                    connectionString: _fixture.ConnectionString,
+                    providerName: _fixture.ProviderName)
+                .WithSqlPersistence(
```
Comment (Aaronontheweb) [inline src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:46]: Config looks good - custom plugin with no default

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs [hunk 6]
```diff
@@ -0,0 +1,275 @@
...
+        protected override async Task BeforeTestStart()
+        {
+            await base.BeforeTestStart();
+            await _fixture.InitializeAsync();
+        }
+
+        protected override void ConfigureAkka(AkkaConfigurationBuilder builder, IServiceProvider provider)
+        {
+            builder
+                .WithSqlPersistence(
```
Comment (Aaronontheweb) [inline src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:43]: Default plugin - looks good.

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs [hunk 7]
```diff
@@ -0,0 +1,275 @@
...
+            var timeout = 3.Seconds();
+
+            #region Default SQL plugin
+            
+            // arrange
+            var myPersistentActor = await ActorRegistry.GetAsync<MyPersistenceActor>();
+
+            // act
+            myPersistentActor.Tell(1, TestActor);
+            ExpectMsg<string>(Ack);
```
Comment (Aaronontheweb) [inline src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:90]: Nitpick: should use async overloads

File: src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs (hunk 3 above)
Comment (Aaronontheweb) [reply src/Akka.Persistence.Sql.Hosting.Tests/CustomSqlEndToEndSpec.cs:173]: LGTM

**Review by Aaronontheweb — COMMENTED** [review]
Where is the actual fix here?

File: src/Akka.Persistence.Sql.Hosting/SqlJournalOptions.cs [hunk 8]
```diff
@@ -154,32 +154,41 @@ protected override StringBuilder Build(StringBuilder sb)
...
-            }
+            if (ReadIsolationLevel is not null)
+                sb.AppendLine($"read-isolation-level = {ReadIsolationLevel.ToHocon()}");
 
             if (QueryRefreshInterval is not null)
-                sb.AppendLine($"akka.persistence.query.journal.sql.refresh-interval = {QueryRefreshInterval.ToHocon()}");
-
+                sb.AppendLine($"refresh-interval = {QueryRefreshInterval.ToHocon()}");
+            
+            sb.AppendLine($"serializer = {Serializer.ToHocon()}");
```
Comment (Aaronontheweb) [inline src/Akka.Persistence.Sql.Hosting/SqlJournalOptions.cs:186]: Why do we need to set a serializer explicitly in this plugin? Haven't we been actively trying to avoid doing this in all other plugins?

Comment (Aaronontheweb) [reply src/Akka.Persistence.Sql.Hosting/SqlJournalOptions.cs:186]: We want to let the `ActorSystem` serialization settings always stay in the driver seat - back in the not-too-distant past, we have an un-overrideable dependency on Newtonsoft.Json hard-coded into Akka.Persistence that was extremely annoying to remove.

File: src/Akka.Persistence.Sql.Hosting/SqlJournalOptions.cs [hunk 9]
```diff
@@ -154,32 +154,41 @@ protected override StringBuilder Build(StringBuilder sb)
...
-            {
-                sb.AppendLine("akka.persistence.query.journal.sql {");
-                sb.AppendLine($"connection-string = {ConnectionString.ToHocon()}");
-                sb.AppendLine($"provider-name = {ProviderName.ToHocon()}");
+            BuildQueryConfig(sb, QueryPluginId);
+            
+            if (IsDefaultPlugin && Identifier is not "sql")
+                BuildQueryConfig(sb, "akka.persistence.query.journal.sql");
+
+            return sb;
```
Comment (Arkatufus) [inline src/Akka.Persistence.Sql.Hosting/SqlJournalOptions.cs:162]: The actual fix.
Before, we included the default fallback but did not do any overrides, that's why the connection string and provider name was empty.
The first `BuildQueryConfig()` line injects all that information.

Comment (Aaronontheweb) [reply src/Akka.Persistence.Sql.Hosting/SqlJournalOptions.cs:162]: LGTM

**Review by Aaronontheweb — APPROVED** [review]
LGTM
