### PR TITLE
Fix query batch size detection failure

### LINKED ISSUE #502: `SqlReadJournal.CurrentAllEvents` completes before emitting all events when used with an `IReadEventAdapter` that drops events
**Version Information**
Version of Akka.NET? 1.5.30
Which Akka.NET Modules? Akka.Persistence.Sql

**Describe the bug**
`SqlReadJournal.CurrentAllEvents` completes before emitting all events when used with an `IReadEventAdapter` that drops events (i.e. by returning `EventSequence.Empty`).

This is due to `hasMoreEvents` in `SqlReadJournal.Events` being set to false when `CurrentJournalEvents` returns a number of events not equal to the max batch size. Since `CurrentJournalEvents` returns adapted events, this can be a false positive if the event adapter does not perform a 1-to-1 mapping.

**To Reproduce**
1. Configure an `IReadEventAdapter` that returns `EventSequence.Empty` for some events
2. Perform a `CurrentAllEvents` query from offset 0 against a journal that a) has more events than the configured batch size (believe this is 500 by default), and b) contains an event in the first batch that will be mapped to `EventSequence.Empty` by the read adapter
3. Observe that the `CurrentAllEvents` query is completed after reading the batch containing the dropped event

**Actual behaviour**
See above

**Expected behaviour**
`CurrentAllEvents` should only complete after reaching end of journal

**Environment**
Windows, .NET 8

**Additional context** https://github.com/akkadotnet/Akka.Persistence.Sql/blob/fff29d16a2ccca2c4be2e88643d77fc7391b644c/src/Akka.Persistence.Sql/Query/SqlReadJournal.cs#L366

https://github.com/akkadotnet/Akka.Persistence.Sql/blob/fff29d16a2ccca2c4be2e88643d77fc7391b644c/src/Akka.Persistence.Sql/Query/SqlReadJournal.cs#L228

### PR DESCRIPTION
**Pull request by Arkatufus**
Fixes #502

An alternate way to #503 for fixing #502

## Changes

* Make `CurrentJournalEvents` to return a stream or `EventEnvelope` array, this way we can still count the actual number of rows returned by the database.
* Add regression spec

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

### CODE REVIEW

File: src/Akka.Persistence.Sql/Query/SqlReadJournal.cs [hunk 1]
```diff
@@ -219,15 +219,15 @@ private Source<EventEnvelope, NotUsed> EventsByPersistenceIdSource(
                             timestamp: r.representation.Timestamp, 
                             tags: r.tags));
 
-        private Source<EventEnvelope, NotUsed> CurrentJournalEvents(long offset, long max, MaxOrderingId latestOrdering)
+        private Source<EventEnvelope[], NotUsed> CurrentJournalEvents(long offset, long max, MaxOrderingId latestOrdering)
```
Comment (Arkatufus) [inline src/Akka.Persistence.Sql/Query/SqlReadJournal.cs:222]: Instead of using `SelectMany` and return a list of `EventEnvelope`s, we use `Select` and return a list of `EventEnvelope[]` arrays instead. This list count will be consistently equals to the number of rows we fetched from the database.

**Review by Arkatufus — COMMENTED** [review]
Self-review

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Review by to11mtm — COMMENTED** [review]
Beautiful. <3
