### PR TITLE
Fix tag mode bug

### LINKED ISSUE #184: Csv and tag table based query configuration isn't being read consistently on all code path
**Describe the bug**
When tag write and read mode is set to TagTable, some code path misread the configuration and still thinks that they are reading from a csv database row instead of tag table.

### PR DESCRIPTION
**Pull request by Arkatufus**
(cherry picked from commit 3198bd6582d4a164ffe1710682669a5fcb060dcd)

Fixes #184

## Changes

- Standardize how tag mode are being read
- Make sure tag modes are being read consistently

### CODE REVIEW

File: src/Akka.Persistence.Sql/Config/JournalConfig.cs [hunk 1]
```diff
@@ -71,6 +73,15 @@ public interface IProviderConfig<TTable>
         string DefaultSerializer { get; }
     }
 
+    public interface IPluginConfig
```
Comment (Arkatufus) [inline src/Akka.Persistence.Sql/Config/JournalConfig.cs:76]: For consistency sake, tag separator and tag mode configuration will be standardized to this interface and being stored inside the `IProviderConfig` config class.

File: src/Akka.Persistence.Sql/Db/AkkaPersistenceDataConnectionFactory.cs [hunk 2]
```diff
@@ -180,7 +180,7 @@ public AkkaPersistenceDataConnectionFactory(IProviderConfig<SnapshotTableConfigu
                 .IsNotColumn();
 
             // We can skip writing tags the old way by ignoring the column in mapping.
-            if (tableConfig.TagWriteMode == TagWriteMode.TagTable)
```
Comment (Arkatufus) [inline src/Akka.Persistence.Sql/Db/AkkaPersistenceDataConnectionFactory.cs:183]: The original bug was here, configuration were not being read because it was stored in two different location, depending on which journal plugin were used.
Instead of using convoluted code to check which journal are being configured, we just standardized how we read our configuration and make sure that this code always points to the right information.

File: src/Akka.Persistence.Sql/Config/JournalPluginConfig.cs [hunk 3]
```diff
@@ -4,18 +4,28 @@
 //  </copyright>
 // -----------------------------------------------------------------------
 
+using System;
+
 namespace Akka.Persistence.Sql.Config
 {
-    public class JournalPluginConfig
+    public class JournalPluginConfig: IPluginConfig
```
Comment (CumpsD) [inline src/Akka.Persistence.Sql/Config/JournalPluginConfig.cs]:
```suggestion
    public class JournalPluginConfig : IPluginConfig
```

File: src/Akka.Persistence.Sql/Config/SnapshotPluginConfig.cs [hunk 4]
```diff
@@ -4,15 +4,19 @@
 //  </copyright>
 // -----------------------------------------------------------------------
 
+using System;
+
 namespace Akka.Persistence.Sql.Config
 {
-    public class SnapshotPluginConfig
+    public class SnapshotPluginConfig: IPluginConfig
```
Comment (CumpsD) [inline src/Akka.Persistence.Sql/Config/SnapshotPluginConfig.cs]:
```suggestion
    public class SnapshotPluginConfig : IPluginConfig
```

File: src/Akka.Persistence.Sql/Config/ReadJournalPluginConfig.cs [hunk 5]
```diff
@@ -8,30 +8,24 @@
 
 namespace Akka.Persistence.Sql.Config
 {
-    public class ReadJournalPluginConfig
+    public class ReadJournalPluginConfig: IPluginConfig
```
Comment (CumpsD) [inline src/Akka.Persistence.Sql/Config/ReadJournalPluginConfig.cs]:
```suggestion
    public class ReadJournalPluginConfig : IPluginConfig
```

File: src/Akka.Persistence.Sql/Config/SnapshotPluginConfig.cs [hunk 6]
```diff
@@ -4,15 +4,19 @@
...
     {
         public SnapshotPluginConfig(Configuration.Config config)
             => Dao = config.GetString(
                 "dao",
                 "Akka.Persistence.Sql.Snapshot.ByteArraySnapshotDao, Akka.Persistence.Sql");
 
         public string Dao { get; }
+        public string TagSeparator => throw new NotImplementedException();
+        public TagMode TagMode => throw new NotImplementedException();
```
Comment (CumpsD) [inline src/Akka.Persistence.Sql/Config/SnapshotPluginConfig.cs]:
```suggestion
        public string Dao { get; }
        
        public string TagSeparator => throw new NotImplementedException();
        
        public TagMode TagMode => throw new NotImplementedException();
```

**Comment by CumpsD** [comment]
LGTM, added some style suggestion you can merge with a single click :)
